---
name: Fuzz Testing

permissions:
  contents: read

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  fuzz_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version: ['5.36', '5.38']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}

      - name: Install dependencies
        run: |
          cpanm --installdeps --with-develop .

      - name: Install App::Test::Generator
        run: |
          cpanm App::Test::Generator

      - name: Generate fuzz tests
        run: |
          fuzz-harness-generator t/conf/online_render.yml > t/online_render_fuzz.t

      - name: Run the generated fuzz test
        run: |
          prove -lv t/online_render_fuzz.t
